### ISSUE TITLE
Actionables from 2024-11-20 reading-club meeting

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rustc-dev-guide#2141]
- [x] remove "identifiers in the compiler" (individual chapters for each ast/ir should just go in detail if warranted)
- [x] move the stuff thats completely unrelated to source code repr to some new header such as "supporting infra" (and probably the closure expansion one to analysis since it basically just talks about type checking lol)
- [ ] #2143
- [x] dont inline all the definitions of inline asm ast/hir/mir/whatever into the dev guide just link to it
- [ ] do we talk about async anywhere lol

See https://rust-lang.zulipchat.com/#narrow/channel/196385-t-compiler.2Fwg-rustc-dev-guide/topic/.5Breading.20club.5D.202024.2E11.2E20.20chapter.2040.20to.2042/near/483542730

**Comment by jieyouxu** [comment]
Two actionables were converted into separate issues.
