### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-dev-guide#48]
Are there any other terms that should be added to the glossary? Please make suggestions.

- [x] filemap (#35)
- [x] soundness (#54)
- [x] completeness (#54)
- [x] skolemization (#67)
- [x] sigil (#57)
- [x] LTO, ThinLTO, FatLTO (#56)
- [x] TLS (#56)
- [x] LLVM (#56)
- [x] IR (#56)
- [x] Fat pointer (#112)
- [x] region (#57)
- [x] HIR map (#63)
- [x] CTFE (compile-time function evaluation)... This just needs a link to the const eval/miri sections (#152)
- [x] rib (see name resolution chapter) (#152)
- [x] upvar (I believe an "upvar" is just a variable captured by a closure) (#152)
- [x] early-bound lifetime (#281)
- [x] interned (#281)
- [x] item (#281)
- [x] late-bound lifetime (#281)
- [x] lang item (#281)
- [x] memoized (#281)
- [x] string interning (#281)
- [x] drop glue (#281)
- [x] late-bound regions/lifetimes (#281)
- [ ] ~gensym~
- [ ] landing pad
- [ ] ~skolemization leak~

**Comment by phansch** [comment]
One thing I have been wondering is if 'soundness' means something special in the compiler context or if it is just a different word for correctness. There are [lot's of issues](https://github.com/rust-lang/rust/search?q=soundness&type=Issues&utf8=%E2%9C%93) mentioning 'soundness bugs' and 'soundness fixes'. So maybe it makes sense to add this too or explain it somewhere?

**Comment by mark-i-m** [comment]
Yes, soundness is a technical term in programming languages literature. You will usually read about proving "soundness" and "completeness".

Roughly, IIRC, soundness means that if a program type-checks, it is type-safe; i.e. I can never (in safe rust) force a value into a variable if the wrong type. Completeness means that every type-safe program also type-checks. Having both is very hard, and usually soundness is more important.

**Comment by samWson** [comment]
I've found a good definition of _Fat Pointers_ in the Programming Rust book. I can enter that in the glossary this weekend if it's OK with you team.

**Comment by steveklabnik** [comment]
We've been using "double pointer" or "wide pointer" as well; might be worth considering as "double pointer" at least is significantly more descriptive, IMO.

**Comment by rkruppe** [comment]
FWIW "double pointer" can also be read as "pointer-to-pointer" (and I've definitely seen it used in that sense in other languages). Besides, *double* becomes inaccurate with custom DSTs (which can add more data than just one word to the pointer). One precise and universal phrase is "pointer with metadata" but that's probably a bit too verbose.

**Comment by samWson** [comment]
Is this a case with of several phrases with the same meaning? Or are these the names of different things?

**Comment by mark-i-m** [comment]
I believe "fat pointer", "wide pointer", and "double pointer" are all intended to be synonyms.

**Comment by samWson** [comment]
I can enter this in the glossary as a single entry e.g. 

Term | Meaning
------|----------------------------------------------------
Fat pointer, wide pointer, double pointer | "definition goes here"

Or I could make them separate entries, each referencing a single definition:

Term | Meaning
------|-----------------
Fat pointer | Two word pointer with address and metadata
Wide pointer | see fat pointer
double pointer | see fat pointer

The second style makes it easier to find each individual term, as it keeps things in alphabetical order.

**Comment by Michael-F-Bryan** [comment]
@samWson I think the second option is best. "Fat pointer" is by far the most popular name for the concept of a pointer with some extra "metadata" attached, so if people want to lookup the term "wide pointer" we should redirect them to the canonical term.

**Comment by mark-i-m** [comment]
Perhaps we could also add that they are used for dyn Trait and slices?

**Comment by samWson** [comment]
@mark-i-m Of course. I'll put in a longer definition in the glossary. I only omitted it in my comment for brevity. I'll have a PR ready soon.

**Comment by samWson** [comment]
Just submitted pull request #112 . Let me know what you think.

**Comment by varkor** [comment]
"Rib" and "upvar" should probably be mentioned too.

**Comment by mark-i-m** [comment]
Yeah, upvar is one that had mystified me too...

**Comment by mark-i-m** [comment]
Is an `upvar` basically a variable that is captured by a closure?

**Comment by varkor** [comment]
DST and ZST might also be worth including.

**Comment by mark-i-m** [comment]
@varkor added in #152

**Comment by varkor** [comment]
It'd be good to explicitly define "item" too, as it's not immediately clear from the source exactly what things can be items.

**Comment by mark-i-m** [comment]
Thanks :)

@varkor would you mind opening a PR for that?

**Comment by alexreg** [comment]
It would be really nice to have a definition for "late-bound regions/lifetimes" in the glossary... I still have no bloody clue what these things are!

**Comment by mark-i-m** [comment]
Unfortunately, there is a lack of people who know definitions to things, so this list is just getting longer... Not sure what to do about that...

**Comment by alexreg** [comment]
I can probably help with some of these... though I wouldn't call myself an authority. Borrow checking is pretty arcane magic as far as I'm concerned. We might have to draft in @nikomatsakis for this. Even if he (or someone like him) could leave comments on this post, then someone could formalise the definitions and create a PR maybe. :-)

**Comment by varkor** [comment]
@alexreg: most of these definitions can be found with a little sleuthing. I think [this post](http://smallcultfollowing.com/babysteps/blog/2013/10/29/intermingled-parameter-lists/) explains early- and late-bound lifetimes, for example.

**Comment by oli-obk** [comment]
There are also some (albeit not necessarily easy to decipher) explanations in the internals docs: https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/enum.RegionKind.html#bound-regions

**Comment by alexreg** [comment]
@varkor @oli-obk Thanks. I'm not very good at searching. There are too many "references" rather than "definitions", which makes grepping harder than it should be.

**Comment by alexreg** [comment]
@mark-i-m Can we add "gensym" to the list please? That's a weird term that I'm still not entirely sure what it means.

**Comment by mark-i-m** [comment]
Added "landing pad" to the list

**Comment by tshepang** [comment]
@alexreg did you refer to [the (now removed) compiler flag](https://github.com/rust-lang/rust/pull/70175) ?

**Comment by alexreg** [comment]
@tshepang I think you meant to take @mark-i-m?

**Comment by tshepang** [comment]
indeed I did

**Comment by tshepang** [comment]
@alexreg what about gensym... [it did itself get removed](https://github.com/rust-lang/rust/pull/64623).

**Comment by alexreg** [comment]
@tshepang Yep, good point. We can remove that from the list now.

**Comment by mark-i-m** [comment]
I think the concept of landing pads still exists... not 100% sure, but I think they are code emitted for unwinding.

**Comment by mark-i-m** [comment]
Closing this in favor of #707
